add tag for BVT on canary testing
open-cluster-management/grc-ui pull request #768
Opened 2021-09-24 03:57 UTC by yahliu

Signed-off-by: yahliu@redhat.com

Relate with the task [13807](https://github.com/open-cluster-management/backlog/issues/13807), the requirement is needing to define automated test cases to be run in the one-hour BVT canary. Add `@bvt` tag to collect the basic cases to verify each policy controller in BVT canary pipeline.  
fyi @drkho

2021-09-24 11:39 UTC, yahliu commented
/cc @dhaiducek

2021-09-27 19:37 UTC, dhaiducek requested changes
The `@extended` tags need to be preserved for current uses. However, you should be able to add the space-separated `@bvt` tag to it.

2021-09-27 19:37 UTC, dhaiducek commented on tests/cypress/tests/CertPolicy_governance.spec.js
> +describeT('@bvt Setup - create a certificate expiring soon', () => {
```suggestion
describeT('@extended @bvt Setup - create a certificate expiring soon', () => {
```

2021-09-27 19:37 UTC, dhaiducek commented on tests/cypress/tests/CertPolicy_governance.spec.js
> +describeT('@bvt RHACM4K-2294 - GRC UI: [P1][Sev1][policy-grc] - CertificatePolicy governance', () => {
```suggestion
describeT('@extended @bvt RHACM4K-2294 - GRC UI: [P1][Sev1][policy-grc] - CertificatePolicy governance', () => {
```

2021-09-27 19:37 UTC, dhaiducek commented on tests/cypress/tests/CertPolicy_governance.spec.js
> +describeT('@bvt RHACM4K-1205 - GRC UI: [P1][Sev1][policy-grc] - CertificatePolicy governance', () => {
```suggestion
describeT('@extended @bvt RHACM4K-1205 - GRC UI: [P1][Sev1][policy-grc] - CertificatePolicy governance', () => {
```

2021-09-27 19:37 UTC, dhaiducek commented on tests/cypress/tests/CertPolicy_governance.spec.js
> +describeT('@bvt Cleanup - delete a certificate and an issuer', () => {
```suggestion
describeT('@extended @bvt Cleanup - delete a certificate and an issuer', () => {
```

2021-09-27 19:37 UTC, dhaiducek commented on tests/cypress/tests/IamPolicy_governance.spec.js
> +describeT('@bvt GRC UI: [P1][Sev1][policy-grc] IamPolicy governance - setup', () => {
```suggestion
describeT('@extended @bvt GRC UI: [P1][Sev1][policy-grc] IamPolicy governance - setup', () => {
```

2021-09-27 19:37 UTC, dhaiducek commented on tests/cypress/tests/IamPolicy_governance.spec.js
> +describeT('@bvt RHACM4K-1719 - GRC UI: [P1][Sev1][policy-grc] IamPolicy governance', () => {
```suggestion
describeT('@extended @bvt RHACM4K-1719 - GRC UI: [P1][Sev1][policy-grc] IamPolicy governance', () => {
```

2021-09-27 19:37 UTC, dhaiducek commented on tests/cypress/tests/IamPolicy_governance.spec.js
> +describeT('@bvt GRC UI: [P1][Sev1][policy-grc] IamPolicy governance - cleanup', () => {
```suggestion
describeT('@extended @bvt GRC UI: [P1][Sev1][policy-grc] IamPolicy governance - cleanup', () => {
```

2021-09-27 19:37 UTC, dhaiducek commented on tests/cypress/tests/Namespace_governance.spec.js
> +describeT('@bvt GRC UI: [P1][Sev1][policy-grc] Namespace policy governance - setup', () => {
```suggestion
describeT('@extended @bvt GRC UI: [P1][Sev1][policy-grc] Namespace policy governance - setup', () => {
```

2021-09-27 19:37 UTC, dhaiducek commented on tests/cypress/tests/Namespace_governance.spec.js
> +describeT('@bvt RHACM4K-1725 - GRC UI: [P1][Sev1][policy-grc] Namespace policy governance', () => {
```suggestion
describeT('@extended @bvt RHACM4K-1725 - GRC UI: [P1][Sev1][policy-grc] Namespace policy governance', () => {
```

2021-09-27 19:37 UTC, dhaiducek commented on tests/cypress/tests/Namespace_governance.spec.js
> +describeT('@bvt GRC UI: [P1][Sev1][policy-grc] Namespace policy governance - clean up', () => {
```suggestion
describeT('@extended @bvt GRC UI: [P1][Sev1][policy-grc] Namespace policy governance - clean up', () => {
```

2021-09-28 14:24 UTC, dhaiducek approved these changes
LGTM!

2021-09-29 01:51 UTC, yahliu commented
@dhaiducek I rebased codes due to conflict，please review it again. Thanks!

2021-09-29 02:39 UTC, yahliu commented
/retest

2021-09-29 14:02 UTC, dhaiducek approved these changes

2021-09-29 14:03 UTC, merged