Clean up acm governance policy creation tooltips
open-cluster-management/grc-ui pull request #798
Opened 2021-10-05 13:59 UTC by ChunxiAlexLuo

https://github.com/open-cluster-management/backlog/issues/14873

Signed-off-by: Chunxi Luo chuluo@redhat.com

2021-10-05 15:18 UTC, ycao56 approved these changes
/lgtm
/hold until confirmed by @dockerymick

2021-10-05 15:45 UTC, dockerymick requested changes
Thanks for making these changes, I left comments for the changes

2021-10-05 15:45 UTC, dockerymick commented on src-web/nls/platform.properties
> +policy.create.namespace.tooltip = Enter the hub cluster namespace where the policy is created and stored
add a period (.) at the end of this statement

2021-10-05 15:45 UTC, dockerymick commented on tests/jest/components/common/TemplateEditor/__snapshots__/TemplateEditor.test.js.snap
> +                      placeholder="Enter the hub cluster namespace where the policy is created and stored"
period needed here

2021-10-05 15:45 UTC, dockerymick commented on tests/jest/components/modules/__snapshots__/CreationView.test.js.snap
> +                          placeholder="Enter the hub cluster namespace where the policy is created and stored"
period needed here

2021-10-05 15:45 UTC, dockerymick commented on tests/jest/components/modules/__snapshots__/CreationView.test.js.snap
> +                          placeholder="Enter the hub cluster namespace where the policy is created and stored"
period needed here

2021-10-05 20:28 UTC, dockerymick approved these changes
Looks good to me! Thanks!

2021-10-06 13:16 UTC, ChunxiAlexLuo commented
/retest

2021-10-06 17:04 UTC, ChunxiAlexLuo commented
/retest

2021-10-06 18:11 UTC, ChunxiAlexLuo commented
/retest

2021-10-07 00:02 UTC, ChunxiAlexLuo commented
/retest

2021-10-07 12:41 UTC, ycao56 commented
/retest

2021-10-07 18:39 UTC, ChunxiAlexLuo commented
/test all

2021-10-08 22:50 UTC, merged